#!/bin/sh

NAME="aesdsocket"
DAEMON="/usr/bin/aesdsocket"
DAEMON_ARGS="-d"
PIDFILE="/var/run/$NAME.pid"

case "$1" in
    start)
        echo -n "Starting $NAME: "
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -d
        
        ;;
    stop)
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal SIGTERM
        rm -f $PIDFILE
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop}"
        exit 1
        ;;
esac

exit 0
